# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Push Docker image'
      inputs:
        command: buildAndPush
        containerRegistry: 'efsoft'
        repository: 'efsoft-products'
        dockerfile: '**/Dockerfile'
        arguments: '--build-arg NUGET_PASSWORD=$(PAT)'
        tags: |
          $(tag)