# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: Delete Existing container if exists
      inputs:
        azureSubscription: 'EFSoft-Subscription(7530e887-c945-44bc-b0bf-fdd3416284f5)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container delete -g efsoft-rg -n efsoft-products --yes
        powerShellErrorActionPreference: 'silentlyContinue'
        
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        containerRegistry: 'efsoft'
        command: 'build'
        repository: 'efsoft-products'
        dockerfile: '**/Dockerfile'
        arguments: '--build-arg NUGET_PASSWORD=$(PAT)'
        tags: $(Build.BuildId)
    - task: Docker@2
      displayName: 'Push Docker image'
      inputs:
        containerRegistry: 'efsoft'
        repository: 'efsoft-products'
        command: 'push'
        tags: $(Build.BuildId)